name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    name: Build, Scan and Push Multiarch Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub (for cache)
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    # STEP 1: build tylko dla amd64, lokalnie
    - name: Build local amd64 image for Trivy scan
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        platforms: linux/amd64
        tags: weather-app:test
        load: true
        cache-from: type=registry,ref=doman782/weather-app-cache
        cache-to: type=registry,ref=doman782/weather-app-cache,mode=max

    # STEP 2: Trivy lokalnie (docker run)
    - name: Run Trivy vulnerability scanner locally
      run: |
        docker run --rm \
          -v /var/run/docker.sock:/var/run/docker.sock \
          aquasec/trivy:0.50.1 image \
          --severity CRITICAL,HIGH \
          --ignore-unfixed \
          --format table \
          --vuln-type os,library \
          --exit-code 1 \
          weather-app:test

    # STEP 3: jeśli Trivy OK buduj multiarch i wypchnij
    - name: Push image to GHCR if scan passes
      if: success()
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/weather-app:latest
        cache-from: type=registry,ref=doman782/weather-app-cache
        cache-to: type=registry,ref=doman782/weather-app-cache,mode=max
